// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace NTPproject
{
    public partial class Account
    {
        public Account()
        {
            Calculators = new HashSet<Calculator>();
        }

        public int UserId { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string EmailAddress { get; set; }
        public DateTime CreatedDate { get; set; }
        public int? Height { get; set; }
        public string DoctorEmail { get; set; }
        public string TrainerEmail { get; set; }

        public virtual ICollection<Calculator> Calculators { get; set; }
    }
}