// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace NTPproject
{
    public partial class Calculator
    {
        public int CalculatorId { get; set; }
        public string CalculatorName { get; set; }
        public string Model { get; set; }
        public int SellerId { get; set; }
        public DateTime CreateDate { get; set; }        
        public string ImagePath { get; set; }
        public string Price { get; set; }
        public int? BuyerId { get; set; }

        public virtual Account Seller { get; set; }
    }
}